//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceF
    {
        public string Cin_F { get; set; }
        public string date_absence { get; set; }
        public Nullable<int> Nombre_Heure { get; set; }
    
        public virtual Formateur Formateur { get; set; }
    }
}
