//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GestionScolariteEntities : DbContext
    {
        public GestionScolariteEntities()
            : base("name=GestionScolariteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbsenceF> AbsenceFs { get; set; }
        public virtual DbSet<Absence> AbsenceS { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<Filiere> Filieres { get; set; }
        public virtual DbSet<Formateur> Formateurs { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Stagiaire> Stagiaires { get; set; }
        public virtual DbSet<CrystalAffiche> CrystalAffiches { get; set; }
    
        public virtual int ProcInsert(Nullable<int> codef, string lib, string typef)
        {
            var codefParameter = codef.HasValue ?
                new ObjectParameter("codef", codef) :
                new ObjectParameter("codef", typeof(int));
    
            var libParameter = lib != null ?
                new ObjectParameter("lib", lib) :
                new ObjectParameter("lib", typeof(string));
    
            var typefParameter = typef != null ?
                new ObjectParameter("typef", typef) :
                new ObjectParameter("typef", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcInsert", codefParameter, libParameter, typefParameter);
        }
    }
}
